name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]

    env:
      API_SECRET_KEY: "test-secret-key"
      API_ALGORITHM: "HS256"
      MQTT_BROKER_URL: "localhost"
      DATABASE_URL: "sqlite+aiosqlite:///./test_iot_device_hub.db"
      PY_COLORS: "1"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-asyncio anyio httpx coverage
      - name: Run tests
        run: pytest -q --maxfail=1 --disable-warnings
